name=input("Enter a String:")
print(f"{name.upper()}  - {name.lower()} - {name.title()} - {name.capitalize()}")
print(f"{len(name)}")
print(f"{name.count("T")}")
print(f"{name.count("T",10)}")
print(f"{name.split()}")
print(f"{name.split("a")}")
print(f"{name.find("s")}")
print(f"{name.replace}")
print(f"{name.strip()}")
print(f"{name.rstrip()}")
print(f"{name.lstrip}")
print(f"{name.startswith("o")}")
